# orca injectables complicate matters because the decorators are executed at module load time
# and since py.test collects modules and loads them at the start of a run
# if a test method does something that has a lasting side-effect, then that side effect
# will carry over not just to subsequent test functions, but to subsequently called modules
# for instance, columns added with add_column will remain attached to orca tables
# pytest-xdist allows us to run py.test with the --boxed option which runs every function
# with a brand new python interpreter
language: python
sudo: false
python:
- '2.7'
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cytoolz numpy pandas pip pytables pyyaml toolz
- source activate test-environment
- pip install orca openmatrix zbox
- pip install pytest pytest-cov coveralls pep8 pytest-xdist
- pip install sphinx numpydoc
- pip install psutil
- pip install activitysim
- pip install .
script:
- py.test --boxed --cov netbuffer --cov-report term-missing
after_success:
- coveralls
- bin/build_docs.sh
notifications:
  slack:
    secure: Dpp+zBrnPGBHXrYWjwHy/bnHvhINfepSIiViwKfBZizBvTDvzSJfu6gCH+/lQ3squF3D4qTWwxB+LQ9V6KTYhuma8vQVisyneI6ARjUI/qgX6aJjuvmDDGPk6DVeDow7+aCLZ8VEHRhSjwy+dv0Ij0rxI6I94xPVwXUkk7ZjcK0=
env:
  global:
  # GH_TOKEN
  #- secure: pd27nfVapj5KSMJhRB8op3S6U1EB9//rsyXEv59mIwYAc6bMLfaUXh6/2D+TMncdMWsbMjIyIvduYEoTbLojrsJNm+nYaCfx5TzAiGGY6zk0LgS/J+oM3TzWa5MN/h4n6z49CQFdnfOp6EGDioJGEhcwJMgqiqZI/2gaZhGWaVtobNGr4nireEp6H2dD3rVriAD6QcPrqRWP5dzE2b7z2+3b+0N0HpR71DtKGWpSbg9xvpHfRGDSBUOUi7JVaReSW+9zNb4U5yCFp+4DnTQoND20tg41i7EYn0RdhNy7CjSlySf6z4Ykmftto4dXobr8aqcAwUuXPvdlJ3GnVal8+qKaqZnvxdTLNdo7mQGt5j7HB790ZdwROtAyxCP8o/htssujibWdbqEnGA87aT9WMUazC2QkVAERNQcH62xy85e1qoyTXYTnyI+0sgdBFM+tZGt4v47RWOEV49RpuW8v2sV7NzFoE2TV+FTjuk6sUVT9EQqACLtVg9Tq34UD37ExxtD+k1ExfRxcS/g/EVjcvxESLeq4gXGIF8YWLQlP7kv1DGDm9HrGQw2srX9xfqIOUEbDLdb7EGz1JPvRMam/zc6Q5qom682iBF+3C2+VP6eMwT8XSkpZneNeubC3cn5eSCWDtSwVjpsDimvXgveXLajAEBoufYZhpvXpOrD1Cow=
