os: linux
dist: xenial
language: python
python:
- '3.7'
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pandana -c conda-forge
- conda activate test-environment
- conda config --show
- conda list
- conda install pytest pytest-cov coveralls pycodestyle
- pip install .
- conda env export
script:
- pycodestyle netbuffer
- py.test --cov netbuffer --cov-report term-missing
after_success:
- coveralls
# Build docs
- pip install sphinx numpydoc sphinx_rtd_theme
- cd docs
- make clean
- make html
- touch _build/html/.nojekyll

deploy:
  provider: pages
  local_dir: docs/_build/html
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: master

