#input data store and skims
store: mtc_asim.h5

skims_file: skims.omx

buffer_network: pandana_network.h5

transit_stops: transit_stops.csv

# trace parcel in buffering
trace_parcels: [1117718, 910777, 673572]
