
store: parcels.h5

models:
  # Cannot initialize the pandana network twice so need to run two Python sessions 
  # AssertionError: Adding more networks than have been reserved
  # - create_network 
  - buffer_parcels