input_table_list:
  - tablename: zone_data
    filename: parcels.h5
    index_col: parcelid
    h5_tablename: parcel_data

network: build
network_settings_file: create_network.yaml

max_dist: 16000 # in meters
zones_lon: xcoord_p
zones_lat: ycoord_p

models:
  - buffer_zones
